-- Parameters: ${USER_NAME}, ${PASSWORD}, ${DB_OWNER}, ${PERM_SPACE_MB}, ${SPOOL_SPACE_MB}
CREATE USER ${USER_NAME} AS
  PERM = ${PERM_SPACE_MB}e6,
  SPOOL = ${SPOOL_SPACE_MB}e6,
  PASSWORD = "${PASSWORD}",
  DEFAULT DATABASE = ${DB_OWNER}
;
