# 파일 경로: .github/dependabot.yml
version: 2
updates:
  # 1. Java (Maven) 종속성 업데이트 설정
  - package-ecosystem: "maven"
    # pom.xml 파일이 있는 디렉토리 (보통 프로젝트의 루트 경로)
    directory: "/"
    # 업데이트 스케줄
    schedule:
      interval: "daily"
    # Java 관련 종속성을 매일 확인하고 PR을 생성
    labels:
      - "dependency"
      - "java"
      - "maven"

  # 2. Docker 이미지 업데이트 설정
  - package-ecosystem: "docker"
    # Dockerfile이 있는 디렉토리 (예: 루트 경로)
    directory: "/"
    # 업데이트 스케줄
    schedule:
      interval: "weekly"
    # Docker 이미지 및 기본 OS 업데이트 (예: FROM alpine:latest)
    labels:
      - "dependency"
      - "docker"
      
  # 3. GitHub Actions에 사용되는 액션 버전 업데이트 (선택 사항)
  - package-ecosystem: "github-actions"
    # 액션 파일이 있는 디렉토리
    directory: "/"
    # 업데이트 스케줄
    schedule:
      interval: "weekly"
    labels:
      - "dependency"
      - "github-actions"
