CREATE TABLE IF NOT EXISTS USERS (
    ID VARCHAR(50) PRIMARY KEY,
    PASSWORD_HASH VARCHAR(100),
    BALANCE BIGINT,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE'
);
CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    TX_ID UUID PRIMARY KEY,
    USER_ID VARCHAR(50),
    AMOUNT BIGINT,
    TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
